model:
  input_embedder:
    name: lstm
    embedding:
      dim: 200
      glove: data/glove/glove.6B.200d.txt
    lstm:
      dim: 164
      layers: 2
    length_embed_dim: 20
    span_features:
      - inside_hidden
      - stern_hidden
      - average_hidden
      - attention_token
      - length
    word_dropout: true

train:
  learning_rate: 0.01
