model:
  input_embedder:
    name: lstm
    embedding:
      dim: 200
      glove: data/glove/glove.6B.200d.txt
    span_features:
      - inside_hidden
      - stern_hidden
      - average_hidden
      - attention_token
      - length
    word_dropout: true
