model:
  name: span
  dropout: 0.2
  representation:
    embedding:
      dim: 200
    lstm:
      dim: 164
      layers: 2
    span_features:
      - inside_hidden
      - attention_token
      - length
    length_embed_dim: 20
  decoder:
    name: edge
    punt_on_training: true
    verify_score: false
    verify_decoder: false
    rescore_prediction: false
    span_detector:
      mlp_layers: 2
      mlp_dim: 200
    edge_detector:
      child_label_scheme: concat
      child_label_embed_size: 150
      projection_size: 200
      mlp_layers: 2
      mlp_dim: 200
    cost_augment: 0.0
  output_layer:
    add_edge_loss: true
    null_weight: 0.2
    verbose: false
