model:
  dropout: 0.2
  decoder:
    name: node
    punt_on_training: true
    verify_score: false
    verify_decoder: false
    rescore_prediction: false
    span_detector:
      mlp_layers: 2
      mlp_dim: 200
    cost_augment: 0.0
  output_layer:
    add_edge_loss: false
    null_weight: 0.4
    dummy_weight: 1.0
    verbose: false
