model:
  dropout: 0.2
  decoder:
    name: edge
    punt_on_training: true
    verify_score: false
    verify_decoder: false
    rescore_prediction: false
    span_detector:
      mlp_layers: 2
      mlp_dim: 200
    edge_detector:
      child_label_scheme: concat
      child_label_embed_size: 150
      projection_size: 200
      mlp_layers: 2
      mlp_dim: 200
    cost_augment: 0.0
  output_layer:
    add_edge_loss: true
    null_weight: 0.2
    verbose: false
