# Base config file. Always use this first.

timing:
  max_epochs: 30

train:
  batch_size: 32
  learning_rate: 0.001
  l2_reg: 0
  gradient_clip: 10

data:
  name: null    # Need to be overwritten

model:
  name: null    # Need to be overwritten
