# Base config file. Always use this first.

timing:
  max_epochs: 30
  save_every: 5
  eval_every: 1

train:
  batch_size: 32
  learning_rate: 0.00001
  l2_reg: 0
  gradient_clip: 10

data:
  name: null    # Need to be overwritten

model:
  name: span
